name: Django Security Check

on:
  push:
    branches:
      - master

env:
  FAIL_LEVEL: WARNING
  ENV_TYPE: venv
  DEP_PATH: requirements.txt
  APP_PATH: /

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Check out master
        uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: Scan Django settings for security issues
        id: check
        uses: victoriadrake/django-security-check@master
      - name: Upload output
        uses: actions/upload-artifact@v2
        with:
          name: security-check-output
          path: security_check.txt
